---

- name: "Install nginx on ubuntu servers"
  hosts: all
  become: true  
  vars:
    lbs: <IP address of nginx load balancer server> 
    nginx_hostname: "lb.mithrams.xyz"
    nginx_user: ubuntu

  tasks:
    - name: "Install nginx"
      apt:
        name:
          - nginx
          - php
        state: present    
        update_cache: true  

    - name: "Delete default nginx file"
      delegate_to: "{{lbs}}"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default      
  
    - name: "Creating Virtualhost For nginx"
      delegate_to: "{{lbs}}"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/nginx/sites-available/{{ nginx_hostname }}.conf"
        owner: root
        group: root

    - name: "Symlink with Configuration file"
      delegate_to: "{{lbs}}"
      file:
        src: "/etc/nginx/sites-available/{{ nginx_hostname }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ nginx_hostname }}.conf"
        state: link 


    - name: "restarting/enabling nginx"
      service:
        name: nginx
        state: restarted
        enabled: true
